### ISSUE TITLE
Editor content gets deleted when clicking a file tab for the first time.

### ISSUE THREAD

**Issue by kansuke231** [ResearchComputing/OIDE#13]
As the title says, when a user writes something in an editor and clicks a file tab above the editor for the first time, the content is erased.

**Comment by zebulasampedro** [comment]
This, along with the editor's tendency to load an incorrect session after refresh, are symptoms of a broken *StateService*.

Currently, the StateService attempts to send state back to the server upon locationChange events, which does not adequately account for all the ways in which a user can leave the editor. In order to finally fix this issue, the StateService will have to be rewritten to follow a better approach.
